### ISSUE TITLE
No 0.5.2 in npmjs.com

### ISSUE THREAD

**Issue by artem1** [bruderstein/unexpected-react#11]
Hello!

Can't find 0.5.2 there https://www.npmjs.com/package/unexpected-react. Did you publish it?
```
0.5.1 is the latest of 10 releases
```

**Comment by bruderstein** [comment]
You're right! Sorry, I think I wanted to clear up some things with the issue (in array-changes), and it turned out to be an issue in unexpected-htmllike. I'll publish 0.5.2, just so that forces the update to unexpected-htmllike. There'll be more updates shortly though as we resolve the array-changes issues (actually a problem how we're using it).

Thanks for reporting!

**Comment by bruderstein** [comment]
Published!  Thanks again!
