### ISSUE TITLE
Assersions always pass using Jest

### ISSUE THREAD

**Issue by richtier** [bruderstein/unexpected-react#12]
I have the following test, which should fail:

```jsx
import unexpected from 'unexpected';
import unexpectedReact from 'unexpected-react';
const expect = unexpected.clone().use(unexpectedReact);
import React from 'react';
import TestUtils from 'react-addons-test-utils';


describe('my suite', () => {
  it('my test', () => {
    class MyComponent extends React.Component {
      render() {
        return (<div a={1} />);
      }
    }
    const renderer = TestUtils.createRenderer();
    renderer.render(<Component />)
    return expect(renderer, 'to have rendered', (<div a={2} />));
});
```

but the console reports that the test passes. It should not pass - `1` does not equal `2`.

I have also tried `TestUtils.renderIntoDocument`, having first made sure I emulate the dom using domino. Same outcome occurs.

My jest config in package.json is as follows:

```json
  "jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "verbose": true,
    "testFileExtensions": ["js", "jsx"],
    "moduleFileExtensions": ["js", "jsx"],
    "testPathIgnorePatterns": ["<rootDir>/node_modules"],
    "modulePathIgnorePatterns": ["<rootDir>/node_modules"],
    "testPathDirs": ["<rootDir>/src/"],
    "unmockedModulePathPatterns": ["<rootDir>/node_modules/.*"]
  }
```

my node version is `v5.6.0`.
my `unexpected` version is `10.8.1`
my `unexpected-resact` version is `0.5.2`
jest is configured to use jasmine.

I followed [this readme](https://github.com/bruderstein/unexpected-react). Am I doing anything obviously wrong?

**Comment by bruderstein** [comment]
My guess is that jasmine doesn't support returning a promise from an `it` block (not sure on this, but can't find anything about it).

Try
```js
describe('my suite', () => {
  it('my test', (done) => {
    class MyComponent extends React.Component {
      render() {
        return (<div a={1} />);
      }
    }
    const renderer = TestUtils.createRenderer();
    renderer.render(<Component />)
    expect(renderer, 'to have rendered', (<div a={2} />))
       .then(() => done())
       .catch(e => done(e));
});
```

I'm not sure on Jasmine's handling of errors passed to `done`, but it's worth a go before I try and reproduce it.  If that doesn't work, and you've got a mini-repo with this all in, that would be really helpful.

The good news is, that for these "synchronous" style tests, expect will fail instantly in the (probably) next version of `unexpected-react`.  I'm nearly confident enough that it all works :)

Then, you'll only need to deal with the promise if you have an asynchronous assertion inside your JSX. e.g. when testing a prop that is itself a promise
```js
return expect(renderer, 'to have rendered', (<div a={ expect.it('to be resolved with', 2) } />));
```
otherwise, the `expect` can be called normally, and will throw normally if there is an error.

**Comment by jkimbo** [comment]
@richtier jest has `hit` whch is a promise helper: https://facebook.github.io/jest/docs/api.html#globally-injected-variables

**Comment by bruderstein** [comment]
@jkimbo I presume you mean `pit`?  That looks perfect, and makes the code much nicer.
@richtier let me know if that works.

**Comment by richtier** [comment]
ah I see I missed the part where `expect` returns a promise. Is `unexpected-react` not aimed to be used with `jasmine`? Should I be using `mocha` instead, for example?

Still not joy though (with jasmine):

```jsx

  it('my test', done => {
    class Component extends React.Component {
      render() {
        return (<div a={1}/>);
      }
    }
    const renderer = TestUtils.createRenderer();
    renderer.render(<Component />)
    return expect(renderer, 'to have rendered', (<div a={2} />))
       .then(done)
       .catch(done)
  })
```

This test still passes. I also tried `pit` but that timed out - most likely because `Jest` is notoriously slow. I will investigate how to set jasmine's `DEFAULT_TIMEOUT_INTERVAL` to a ridiculously high value.

I tried `unexpected-react-shallow` - and it the test fails correctly because it avoids the `jest` vs `pit` woes because `unexpected-react-shallow` does not return promises. I will use that for now until "expect will fail instantly in the (probably) next version of unexpected-react".

**Comment by bruderstein** [comment]
It will pass, because even if an error is thrown, you're still calling `done`. You need to do something with the error. Obviously passing the error to `done` doesn't do the trick.

There are a few options:
1.  Try with `pit` instead of `it` (that looks like it should work from the [code from jasmine-pit](https://github.com/jeffmo/jasmine-pit/blob/master/index.js#L49))
2. Use mocha instead of jasmine, and return the promise
3. Use unexpected-react-shallow or the new version when it's available (I'm hopeful for this week, but I thought that a couple of weeks ago too!)

**Comment by richtier** [comment]
great, thanks for the help. I will choose option 4 :)
