### ISSUE TITLE
How does this compare with jsdomify?

### ISSUE THREAD

**Issue by faceyspacey** [bruderstein/unexpected-react#3]
https://github.com/podio/jsdomify
https://medium.com/podio-engineering-blog/from-karma-to-mocha-with-a-taste-of-jsdom-c9c703a06b21

What's the difference between the 2 setups? Pros/Cons??

**Comment by bruderstein** [comment]
You can use unexpected-react with jsdomify - they're not two setups. In fact, unexpected-react requires an emulated DOM, so jsdomify is a nice solution.

I don't think it would work if you do the `jsdomify()` call in a `beforeEach()`, I think you'd need to do that globally, and first, at least if you want to use the full renderer (if you're just using the shallow renderer, you don't need the DOM in the first place). 

This is because `unexpected-react` (or rather, `react-render-hook`) installs a hook into window, and that is only done the first time react is required.  It might work, but I suspect you'd hit issues.  However, I'm 99% certain it should "just work" if you start `jsdomify()` at the top of your file.  

I'll try and setup a sample repo with this setup over the weekend and check what works and what doesn't.

**Comment by faceyspacey** [comment]
so, the non-shallow version that just started working (yay!) uses regular `jsdom` behind the scenes via `react-render-hook` correct? 

What would I get by using jsdomify? 

One of the main things is that `jsdomify` seems to have a `compat` version for Node v0.10. I'm trying to get this all working with Meteor which hasn't yet upgraded to v4. Does `unexpected-react` have a "compat" version as well?

**Comment by bruderstein** [comment]
There is no dependency on `jsdom`. You have to ensure a DOM is available, before requiring react. If you're on node 0.x, you'll need jsdom@3.x, but it's up to the project which wants to use `unexpected-react` to decide what to use. You can also use `domino`, which works everywhere, and is a bit faster (I believe), but doesn't have all the features of jsdom. It works fine with react though, and if all you need it for is that, then it's worth trying.

**Comment by faceyspacey** [comment]
what DOM is the example repo using for `Select.spec.js`? Domino and jsom are both dependencies of the main unexpected-react package but in `Select.spec.js` I only see `react-dom` being required.

**Comment by bruderstein** [comment]
It's in the `emulateDom.js` file, required at the top of the tests.

**Comment by bruderstein** [comment]
I've created a `jsdomify` branch in the `unexpected-react-example` project, so you can see where you would use it. Note that it's a little different than their example, because we need the specific order of requires (DOM emulation, unexpected-react, react), and if you clear the DOM globals (e.g. window and document), you won't be able to run any other tests afterwards, as react caches a few DOM nodes initially, and therefore will attempt to use a node created in a different "document".

Have a look at the commit to see how to use it, and what jsdomify brings.

https://github.com/bruderstein/unexpected-react-example/commit/13d6968a1b6ad71783c4291bcd3327b457e6a67e
